In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Clean_Data_pakwheels.csv')
df

,Unnamed: 0,Company Name,Model Name,Price,Model Year,Location,Mileage,Engine Type,Engine Capacity,Color,Assembly,Body Type,Transmission Type,Registration Status
0,0,Toyota,Vitz,2385000,2017,Islamabad,9869,Petrol,1000,Silver,Imported,Hatchback,Automatic,Un-Registered
1,1,Toyota,Corolla,111000,2019,KPK,11111,Petrol,1300,White,Local,Sedan,Automatic,Registered
2,2,Suzuki,Alto,1530000,2019,KPK,17500,Petrol,660,White,Local,Hatchback,Automatic,Un-Registered
3,3,Suzuki,Alto,1650000,2019,Punjab,9600,Petrol,660,White,Local,Hatchback,Manual,Registered
4,4,Toyota,Corolla,1435000,2010,Islamabad,120000,Petrol,1300,Black,Local,Sedan,Manual,Registered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46017,46018,Honda,Vezel,3400000,2015,Punjab,32000,Petrol,1500,Black,Imported,Cross Over,Automatic,Un-Registered
46018,46019,Toyota,Aqua,2450000,2015,Punjab,52000,Petrol,1500,Blue,Imported,Hatchback,Automatic,Un-Registered
46019,46020,Honda,Civic,3250000,2015,Punjab,125000,Petrol,1800,Black,Local,Sedan,Automatic,Registered
46020,46021,Toyota,Aqua,3000000,2016,Punjab,60000,Petrol,1500,Black,Imported,Hatchback,Automatic,Registered
46021,46022,Toyota,Corolla,2250000,2015,Punjab,77000,Petrol,1300,Assembly,Local,Sedan,Automatic,Registered

In [4]:
df.head()

,Unnamed: 0,Company Name,Model Name,Price,Model Year,Location,Mileage,Engine Type,Engine Capacity,Color,Assembly,Body Type,Transmission Type,Registration Status
0,0,Toyota,Vitz,2385000,2017,Islamabad,9869,Petrol,1000,Silver,Imported,Hatchback,Automatic,Un-Registered
1,1,Toyota,Corolla,111000,2019,KPK,11111,Petrol,1300,White,Local,Sedan,Automatic,Registered
2,2,Suzuki,Alto,1530000,2019,KPK,17500,Petrol,660,White,Local,Hatchback,Automatic,Un-Registered
3,3,Suzuki,Alto,1650000,2019,Punjab,9600,Petrol,660,White,Local,Hatchback,Manual,Registered
4,4,Toyota,Corolla,1435000,2010,Islamabad,120000,Petrol,1300,Black,Local,Sedan,Manual,Registered

In [5]:
df.tail()

,Unnamed: 0,Company Name,Model Name,Price,Model Year,Location,Mileage,Engine Type,Engine Capacity,Color,Assembly,Body Type,Transmission Type,Registration Status
46017,46018,Honda,Vezel,3400000,2015,Punjab,32000,Petrol,1500,Black,Imported,Cross Over,Automatic,Un-Registered
46018,46019,Toyota,Aqua,2450000,2015,Punjab,52000,Petrol,1500,Blue,Imported,Hatchback,Automatic,Un-Registered
46019,46020,Honda,Civic,3250000,2015,Punjab,125000,Petrol,1800,Black,Local,Sedan,Automatic,Registered
46020,46021,Toyota,Aqua,3000000,2016,Punjab,60000,Petrol,1500,Black,Imported,Hatchback,Automatic,Registered
46021,46022,Toyota,Corolla,2250000,2015,Punjab,77000,Petrol,1300,Assembly,Local,Sedan,Automatic,Registered

In [6]:
df.columns

Index(['Unnamed: 0', 'Company Name', 'Model Name', 'Price', 'Model Year',
       'Location', 'Mileage', 'Engine Type', 'Engine Capacity', 'Color',
       'Assembly', 'Body Type', 'Transmission Type', 'Registration Status'],
      dtype='object')

In [7]:
df.describe()

,Unnamed: 0,Price,Model Year,Mileage,Engine Capacity
count,46022.000000,4.602200e+04,46022.000000,46022.000000,46022.000000
mean,23010.526205,2.014153e+06,2011.035374,90965.128243,1313.115575
std,13285.595581,2.939071e+06,6.399403,63656.656034,614.690832
min,0.000000,1.110000e+05,1990.000000,1.000000,16.000000
25%,11505.250000,8.500000e+05,2007.000000,48899.500000,1000.000000
50%,23010.500000,1.450000e+06,2013.000000,80000.000000,1300.000000
75%,34515.750000,2.300000e+06,2016.000000,120000.000000,1500.000000
max,46022.000000,7.750000e+07,2019.000000,999999.000000,6600.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46022 entries, 0 to 46021
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           46022 non-null  int64
 1   Company Name         46022 non-null  object
 2   Model Name           46022 non-null  object
 3   Price                46022 non-null  int64
 4   Model Year           46022 non-null  int64
 5   Location             46022 non-null  object
 6   Mileage              46022 non-null  int64
 7   Engine Type          46022 non-null  object
 8   Engine Capacity      46022 non-null  int64
 9   Color                46022 non-null  object
 10  Assembly             46022 non-null  object
 11  Body Type            46022 non-null  object
 12  Transmission Type    46022 non-null  object
 13  Registration Status  46022 non-null  object
dtypes: int64(5), object(9)
memory usage: 4.9+ MB

In [9]:
df.count()

Unnamed: 0             46022
Company Name           46022
Model Name             46022
Price                  46022
Model Year             46022
Location               46022
Mileage                46022
Engine Type            46022
Engine Capacity        46022
Color                  46022
Assembly               46022
Body Type              46022
Transmission Type      46022
Registration Status    46022
dtype: int64

In [10]:
df["Company Name"].unique()

array(['Toyota', 'Suzuki', 'Honda', 'Mitsubishi', 'Nissan', 'Daihatsu',
       'Audi', 'Chevrolet', 'Mercedes', 'Hyundai', 'Daewoo', 'BMW', 'FAW',
       'Range', 'DFSK', 'KIA', 'Lexus', 'United', 'SsangYong', 'Mazda',
       'Subaru', 'Porsche', 'Chery', 'Fiat', 'Land', 'MINI', 'Hummer',
       'Jeep', 'Jaguar', 'Adam', 'Volvo'], dtype=object)

In [11]:
df.nunique()

Unnamed: 0             46022
Company Name              31
Model Name               196
Price                   1419
Model Year                30
Location                   6
Mileage                 5573
Engine Type                3
Engine Capacity           75
Color                     24
Assembly                   2
Body Type                  6
Transmission Type          2
Registration Status        2
dtype: int64

In [12]:
df.isnull()

,Unnamed: 0,Company Name,Model Name,Price,Model Year,Location,Mileage,Engine Type,Engine Capacity,Color,Assembly,Body Type,Transmission Type,Registration Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46017,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46018,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46019,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46021,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Unnamed: 0             0
Company Name           0
Model Name             0
Price                  0
Model Year             0
Location               0
Mileage                0
Engine Type            0
Engine Capacity        0
Color                  0
Assembly               0
Body Type              0
Transmission Type      0
Registration Status    0
dtype: int64